[workspace]
members = [
    "crates/move-language-server",
    "crates/move-build",
    "crates/analysis",
    "crates/dialects",
    "crates/utils",
    "crates/integration_tests",
    "crates/syntax",
]
