[package]
name = "integration_tests"
version = "0.1.0"
authors = ["Maksim Kurnikov <maxim.kurnikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.7.1"

anyhow = "1.0.34"
lsp-types = {version = "0.77.0", features = ["proposed"]}
serde_json = "1.0.52"
lsp-server = "0.3.2"

crossbeam-channel = "0.4.2"
threadpool = "1.8.1"
ra_vfs = "0.6.1"

dialects = { path = "../dialects" }
utils = { path = "../utils" }
analysis = { path = "../analysis" }
move-language-server = { path = "../move-language-server" }
